# Generated by Django 5.2.10 on 2026-01-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_class_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="class_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.classsection",
            ),
        ),
    ]
